# Generated by Django 4.2.5 on 2023-10-08 15:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Fileinfo",
            fields=[
                (
                    "file_number",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "file_name",
                    models.CharField(default="default_filename", max_length=200),
                ),
                ("file_url", models.URLField()),
                ("upload_date", models.DateField(auto_now_add=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=200, null=True)),
                ("country", models.CharField(blank=True, max_length=200, null=True)),
                ("province", models.CharField(blank=True, max_length=200, null=True)),
                ("city", models.CharField(blank=True, max_length=200, null=True)),
                ("district", models.CharField(blank=True, max_length=200, null=True)),
                ("time", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
